### ISSUE TITLE
Flash add does not add all links that have been marked by user

### ISSUE THREAD

**Issue by godfuture** [pyload/pyload-bookmarklet#10]
I was testing first method (flash add) to send multiple links from website
1. Visit a website with multiple links
2. Mark all links that should be added in package
3. Click the bookmarklet
4. Tick "All" to activate all links shown in the list
5. Send package to pyload
6. Check, if all links were added to package (in my case only on link added)

**Comment by godfuture** [comment]
Hi! I just have tested it, but always the last link of my selection was added (You can try [here](https://mygully.com/showpost.php?p=37138755&postcount=3)).

**Comment by GammaC0de** [comment]
You need to update pyload too, have you done that?
