### ISSUE TITLE
Is it possible send to bookmarklet highlighted links?

### ISSUE THREAD

**Issue by savonarola27** [pyload/pyload-bookmarklet#4]
I am trying to use the bookmarklet (FireFox on macOS) but it can see links "hidden".

I am using it on page of a website that show the links of my interest only after I click on a button. Both before and after I click on the button bookmarklet don't see them.

Unfortunately is a site with registration so I can't give you but if it can be useful I can post here the source code of the page.

To bypass this issue, is possible to highlight links and tell bookmarklet to only consider them?

Let me know.

**Comment by GammaC0de** [comment]
Without seeing the specific website I cannot tell, sorry.

**Comment by savonarola27** [comment]
Yes, you are right.

The website is this (http://laforestaincantata.org) maybe if you want you can register.

This is an example of page with hidden text (visible after click on the button "Mostra Link" but you must first click on the big ping to shoe the frame).

However the best would be the possibility to send only highlighted links to the bookmarklet :)

**Comment by GammaC0de** [comment]
Sorry, cannot register.

**Comment by savonarola27** [comment]
Ok, I will try to find a different website (accessible) with the same issue.

However what about operate on a highlighted selection?


Il giorno lun 3 giu 2019 alle ore 20:03 GammaC0de <notifications@github.com>
ha scritto:

**Comment by GammaC0de** [comment]
> However what about operate on a highlighted selection?

What do you mean by that?

**Comment by savonarola27** [comment]
One good thing world be the possibility to highlight a bunch of links as
the following:

http://www.easybytez.com/example1
http://www.easybytez.com/example2
http://www.easybytez.com/example3

and then have a way to tell bookmarklet "download only the highlighted
links".

I hope I explained myself.

Il giorno lun 3 giu 2019 alle ore 20:08 GammaC0de <notifications@github.com>
ha scritto:
