### ISSUE TITLE
Error unauthorized

### ISSUE THREAD

**Issue by domignace** [pyload/pyload-bookmarklet#7]
Hello,

I'm trying to setup pyload-ng with ssl and use it with bookmarklet.

I'm using linuxserver/pyload-ng latest docker image, ssl setup, webgui is working on https://ip:18000.
When sending a link to pyload with bookmarklet, I get an error unauthorized.
FF is 103.0.1, in the bowser console, I am getting:
`LoginHelper(Content): Couldn't parse origin for about:blank <unavailable> [LoginHelper.jsm:665:16](resource://gre/modules/LoginHelper.jsm)
Use of nsIFile in content process is deprecated. [NetUtil.jsm:253:8](resource://gre/modules/NetUtil.jsm)
[Exception... "Component returned failure code: 0x805e0006 (NS_ERROR_CONTENT_BLOCKED) [nsIChannel.asyncOpen]"  nsresult: "0x805e0006 (NS_ERROR_CONTENT_BLOCKED)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 188"  data: no] [FaviconLoader.jsm:188:20](resource:///modules/FaviconLoader.jsm)`

Is there any firefox setup to modify to make bookmarklet work on my setup ?

Regards,
  ++dom

**Comment by domignace** [comment]
Hello @GammaC0de ,

I tried the following image though I don't know how to check that it includes your last commit https://github.com/pyload/pyload/commit/0628198bf5b0fb66c6d742bbe82e7c57cebb2270 :
lscr.io/linuxserver/pyload-ng   develop              3eb1007008e5   3 days ago     327MB

Unfortunately, it does not work. At first, I thought it was a client configuration issue. I tried to use the API with curl.
I am using the following command to test:
`curl -vvvv -k "https://192.168.2.138:18000/api/addPackage" -H 'Content-Type: application/json'   -d '{name: "file", links: ["downloadlink"], "u": "user", "p": "password" }'`

`*   Trying 192.168.2.138:18000...
* Connected to 192.168.2.138 (192.168.2.138) port 18000 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=FR; ST=France; L=Paris; O=Internet Widgits Pty Ltd
*  start date: Mar 12 20:57:28 2022 GMT
*  expire date: Feb 16 20:57:28 2122 GMT
*  issuer: C=FR; ST=France; L=Paris; O=Internet Widgits Pty Ltd
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /api/addPackage HTTP/1.1
> Host: 192.168.2.138:18000
> User-Agent: curl/7.83.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 126
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 UNAUTHORIZED
< Content-Type: application/json
< Content-Length: 25
< Vary: Accept-Encoding
< Date: Sun, 07 Aug 2022 12:51:34 GMT
< Server: Cheroot/8.6.0
< 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{"error":"Unauthorized"}
* Connection #0 to host 192.168.2.138 left intact
`
I tried that command in several places, LAN, on the NAS, in the container (with localhost), I always have the error unauthorized. I also tried to use username/password instead of u and p. Did I missed something ? 

Do you have any clue on how to investigate this ?

**Comment by SMAW** [comment]
Same issue here, hope somebody can get this working.

**Comment by GammaC0de** [comment]
The correct command is:
```
curl --user test:test -X POST "https://192.168.2.138:18000/api/addPackage" -H "Content-Type: application/x-www-form-urlencoded" -d "u=user&p=password&name='file'&links=['downloadlink']"
```

Please test

**Comment by domignace** [comment]
> ```
> curl -X POST "https://192.168.2.138:18000/api/addPackage" -H "Content-Type: application/x-www-form-urlencoded" -d "u=user&p=password&name='file'&links=['downloadlink']"
> ```
> 
> 
>     
>   
> 
> Please test

@GammaC0de , 

Thank you,  the curl command worked.  The bookmarklet is also working now.
